"""Grammar progression planning with dependency validation.

This module keeps grammar sequencing language-agnostic by operating on generic
grammar-topic records and dependency ids.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml

from course_compiler.generation.validator import CEFR_ORDER


class GrammarDependencyError(RuntimeError):
    """Raised when grammar dependencies are invalid or cyclic."""


@dataclass(frozen=True)
class GrammarTopic:
    """A grammar unit that can depend on earlier grammar units."""

    id: str
    language: str
    title: str
    cefr: str
    depends_on: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class GrammarPlan:
    """An ordered grammar topic plus its English authoring hints.

    Mirrors :class:`~course_compiler.generation.themes.LessonThemePlan`: the
    ``topic`` carries the language-agnostic record consumed by the planner, while
    ``focus``/``introduced_in_lesson`` are catalog hints used by the writer to
    steer the explanation and pick the allowed vocabulary.
    """

    topic: GrammarTopic
    focus: str = ""
    introduced_in_lesson: int | None = None


class GrammarProgressionPlanner:
    """Produce an acyclic, deterministic grammar progression order."""

    def plan(self, topics: list[GrammarTopic]) -> list[GrammarTopic]:
        """Return topics ordered so dependencies always come first.

        Raises:
            GrammarDependencyError: For unknown dependencies or dependency cycles.
        """
        by_id = {topic.id: topic for topic in topics}
        if len(by_id) != len(topics):
            raise GrammarDependencyError("Duplicate grammar topic id detected.")

        for topic in topics:
            for dep in topic.depends_on:
                if dep not in by_id:
                    raise GrammarDependencyError(
                        f"Unknown dependency {dep!r} referenced by grammar topic {topic.id!r}."
                    )

        in_degree: dict[str, int] = {topic.id: 0 for topic in topics}
        outgoing: dict[str, set[str]] = {topic.id: set() for topic in topics}

        for topic in topics:
            for dep in topic.depends_on:
                outgoing[dep].add(topic.id)
                in_degree[topic.id] += 1

        ready = sorted([topic_id for topic_id, degree in in_degree.items() if degree == 0])
        ordered_ids: list[str] = []

        while ready:
            current = ready.pop(0)
            ordered_ids.append(current)
            for follower in sorted(outgoing[current]):
                in_degree[follower] -= 1
                if in_degree[follower] == 0:
                    ready.append(follower)
            ready.sort()

        if len(ordered_ids) != len(topics):
            blocked = sorted(topic_id for topic_id, degree in in_degree.items() if degree > 0)
            raise GrammarDependencyError(
                "Grammar dependency cycle detected; unresolved topics: " + ", ".join(blocked)
            )

        return [by_id[topic_id] for topic_id in ordered_ids]


def _levels_up_to(cefr: str) -> list[str]:
    """Return CEFR levels from the lowest up to and including *cefr*."""
    try:
        cutoff = CEFR_ORDER.index(cefr)
    except ValueError:
        return [cefr]
    return CEFR_ORDER[: cutoff + 1]


def load_grammar_catalog(
    path: Path | str, *, language: str, cefr: str
) -> list[GrammarPlan]:
    """Load and dependency-order grammar topics for *cefr*.

    The catalog is a CEFR-keyed YAML (like ``themes.yaml``) mapping topic ids to
    ``{title, dependsOn, introducedInLesson, focus}``. All levels up to and
    including *cefr* are loaded so cross-level dependencies validate and order
    correctly, but only pages for the requested *cefr* are returned (lower
    levels are generated by their own runs).

    Raises:
        GrammarDependencyError: For duplicate ids, unknown deps, or cycles.
    """
    loaded = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        return []

    topics: list[GrammarTopic] = []
    hints: dict[str, GrammarPlan] = {}
    for level in _levels_up_to(cefr):
        block = loaded.get(level)
        if not isinstance(block, dict):
            continue
        for topic_id, data in block.items():
            if not isinstance(topic_id, str) or not isinstance(data, dict):
                continue
            depends_on = data.get("dependsOn") or data.get("depends_on") or []
            topic = GrammarTopic(
                id=topic_id,
                language=language,
                title=str(data.get("title") or topic_id),
                cefr=level,
                depends_on=[str(d) for d in depends_on],
            )
            topics.append(topic)
            lesson = data.get("introducedInLesson", data.get("introduced_in_lesson"))
            hints[topic_id] = GrammarPlan(
                topic=topic,
                focus=str(data.get("focus") or ""),
                introduced_in_lesson=int(lesson) if lesson is not None else None,
            )

    ordered = GrammarProgressionPlanner().plan(topics)
    return [hints[t.id] for t in ordered if t.cefr == cefr]
